### ISSUE TITLE
doe: ipopt crash

### ISSUE THREAD

**Issue by DavidWalz** [experimental-design/bofire#132]
Not certain if this is bofire specific, but the ipop dependency OMP crashes consistently both in a new conda env and in conda env where https://github.com/basf/doe works fine.
```
from bofire.domain.domain import Domain
from bofire.domain.features import (
    ContinuousInput,
)
from bofire.strategies.doe.design import find_local_max_ipopt

p = Domain(
    input_features=[
        ContinuousInput(key="x1", lower_bound=-1, upper_bound=1),
        ContinuousInput(key="x2", lower_bound=-1, upper_bound=1),
        ContinuousInput(key="x3", lower_bound=0, upper_bound=1),
    ],
    constraints=[]
)

find_local_max_ipopt(p, "linear")
```
```
OMP: Error #15: Initializing libomp.dll, but found libiomp5md.dll already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
```
@dlinzner-bcs have you encountered something like this?

**Comment by DavidWalz** [comment]
The often proposed workaround also works here
```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
Still wondering why this only occurs in `bofire.strategies.doe`

**Comment by jduerholt** [comment]
Very strange, I do not had problems. Also no problems in the test pipeline where we also test ipopt related stuff.

**Comment by WaStCo** [comment]
Could be specific for your Windows installation. OpenMP has two names for the same DLL there. May want to rename (doubt though that you are calling it directly) or ignore with the environment variable as you did.

As @jduerholt , I could not replicate.

See this [SO answer](https://stackoverflow.com/a/71260917).

Could you confirm that you have both DLLs? If so, we could add a note somewhere explaining this (although not sure if a catch all or too specific).

**Comment by DavidWalz** [comment]
Thanks for checking @WaStCo!
Both dlls are present. As both dlls have the same checksum, I think it's safe to assume that the `KMP_DUPLICATE_LIB_OK` flag does not cause issues.

**Comment by rosonaeldred** [comment]
Alternate solution: [just delete one of the libraries](https://www.programmersought.com/article/53286415201/).
