### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by DavidWalz** [experimental-design/bofire#16]
Placing the strategy implementations in `bofire` will draw in a large number of dependencies:

* Most model-based strategies will be based on `botorch` and `torch` which are large dependencies 
* TSEMO will additionally pull in `pymoo` and its dependencies
* DOptimal will pull in `ipopt` and the actual ipopt solver, as well as `formulaic`

In my opinion packages such as `summit` suffer when there are two many dependencies because it becomes a barrier for adoption and there is something like a factorial scaling of the probability of version conflicts. 
Therefore I think we should use optional dependencies.

About `botorch` I'm open either way: it's big but it's also going to be used in lots of places.

ping @jduerholt @jkleinekorte @bertiqwerty

**Comment by jduerholt** [comment]
Hi David,

I share your opinion. Once I tried `summit`, it ended up going through the source code and commenting out all dependencies which were not necessary for the thing which I needed.

I never really used optional dependencies in python, how would it work?

Putting in the module files the imports always in a try except and throwing an error when a dependency is not available? How would it work within pip?

Btw, I think also `entmoot` will bring extra dependencies like `xgboost` and gurobi or?

Concerning botorch, I would keep it as mandatory dependency as there will be a lot of stuff depending on it.

Best,

Johannes

**Comment by DavidWalz** [comment]
This is how we are doing it in brain:
* in the setup.py you define the dependency as optional https://github.com/basf/mbo/blob/main/setup.py
* in the import there is try clause https://github.com/basf/mbo/blob/main/mbo/algorithm/__init__.py

**Comment by jduerholt** [comment]
I like the approach, let's do it like this!

**Comment by DavidWalz** [comment]
Question resolved.
