### ISSUE TITLE
 UserWarning: The minimum number of experiments is **, but the current setting is n_experiments = **

### ISSUE THREAD

**Issue by rosonaeldred** [experimental-design/bofire#162]
Ran into this warning, could use help in calling doe correctly 

https://github.com/experimental-design/bofire/blob/d0f4d76dd08dab256ffa9fe47dbf1e0623c17c66/bofire/strategies/doe/design.py#L237

'  UserWarning: The minimum number of experiments is 25, but the current setting is n_experiments=16.
  warnings.warn('

**Comment by Osburg** [comment]
This warning occurs if the user defined number of experiments is smaller than the number of model terms + 3. A smaller number does not have negative effects on the optimization. The warning should only indicate the user might want to reconsider the usefulness of the design to fit the given model to it. You can ignore the warning, if you are sure about the number of experiments you have set for your design.

**Comment by rosonaeldred** [comment]
Context: I'm generating plausible experiments. I choose randomly my model type from ["linear", "linear-and-interactions", "linear-and-quadratic", "fully-quadratic"] and randomly the number of input features. 

Given this, what I really care is the number of experiments is not too large, thus the specification. 
It looks like this (up to fiddlying) is the solution: 
https://github.com/experimental-design/bofire/blob/d0f4d76dd08dab256ffa9fe47dbf1e0623c17c66/bofire/strategies/doe/design.py#L211

Assume defined domain and model_type, what_rosona_specified is some integer: 

```
from doe import get_n_experiments

min_experiments = get_n_experiments(domain, model_type)
num_experiments = max (min_experiments , what_rosona_specified) 

 df = find_local_max_ipopt(domain, model_type, n_experiments=num_experiments )
```
