### ISSUE TITLE
doe error 'No feasible point found. Constraint polytope appears empty. Check your constraints.' Honestly not very helpful. Maybe a tutorial to explore this topic? 

### ISSUE THREAD

**Issue by rosonaeldred** [experimental-design/bofire#163]
https://github.com/experimental-design/bofire/blob/d0f4d76dd08dab256ffa9fe47dbf1e0623c17c66/tests/bofire/strategies/doe/test_design.py#L397

Developed my own "fake doe generator" for a simulation, not necessarily keen on including it in this repo, but we can talk about it in the hackathon and how to fix things so i run into this error less often, or fix doe so it spits it out less often ;)

**Comment by Osburg** [comment]
I think you are right and the problem is that the set of feasible points is empty since even if you are at the lower bound with all variables their sum is 0.22 + 0.29 + 0.24 + 0.29 + 0.17 + 0.13 = 1.34 > 1.

**Comment by rosonaeldred** [comment]
Thanks for braining for me. I blocked 0 minimum because i kept getting that, clearly need to adjust that and/or develop a check that the domain 'makes sense' prior to asking for a doe and then react to that.

**Comment by DavidWalz** [comment]
Hi @rosonaeldred can this issue be closed given there is another ticket #165 ?
