### ISSUE TITLE
doe: add more optimality criteria

### ISSUE THREAD

**Issue by Osburg** [experimental-design/bofire#164]
Autodiff/symbolic differentiation as it is now used for the evaluation of the jacobian of the objective function for D-optimal designs can also be applied to other optimality criteria (e.g. the ones mentioned [here](https://en.wikipedia.org/wiki/Optimal_design)). So far, objective functions other than D-optimality are not implemented because their jacobians were not easy to determine analytically. With automatic differentiation we do not have this problem anymore. I already started implementing some additional optimality criteria and did a few successful small experiments. Finishing this could be a nice thing to do during the hackathon, if you guys think that new optimality criteria could be useful.

**Comment by jduerholt** [comment]
Great idea!

**Comment by DavidWalz** [comment]
Closed with #173. Thanks @Osburg!
