### ISSUE TITLE
Tag for v0.0.3? 

### ISSUE THREAD

**Issue by dwillhelm** [experimental-design/bofire#211]
Can you point to a commit corresponding to latest 0.0.3 (I'm stuck on Python 3.8)

**Comment by jduerholt** [comment]
Hi @dwillhelm, unfortunately there is not really a usable version before 0.0.4. Regarding python 3.8 and python 3.9. Is there no possibility to upgrade to 3.9?

cc @bertiqwerty

**Comment by dwillhelm** [comment]
Unfortunately I am stuck with 3.8 for the moment. 
But I am grateful to see #213! 😄

**Comment by bertiqwerty** [comment]
Hi @dwillhelm, You should be able to use Python 3.8 now if you install from the main branch.

**Comment by dwillhelm** [comment]
> Hi @dwillhelm, You should be able to use Python 3.8 now if you install from the main branch.

Great news! Thanks @bertiqwerty @jduerholt
