### ISSUE TITLE
Move DoE Documentation

### ISSUE THREAD

**Issue by jduerholt** [experimental-design/bofire#215]
Hi @Osburg,

what do you think about moving/copying the documentation of the old DoE package to BoFire? 

Any objections?

Best,

Johannes

**Comment by Osburg** [comment]
Hey @jduerholt :) good idea. Let's do this. I think we should also update it / add information about new features, because quite a lot of things has changed since the documentation of the old doe was written. You can assign this issue to me, then I will take care of it somewhen these days.
cheers, Aaron :)

**Comment by jduerholt** [comment]
Hi @Osburg, thanks!

How should we structure it? Create a high level menu point for the DoE functionality? 

I would recommend to include the examples for DoE as juypter notebooks as I did it for the "getting started", this makes it easier with testing ;)

We should also then mention the possibility to use it as strategy.

Best,

Johannes

**Comment by Osburg** [comment]
What do you think about one subsection for doe in the Getting Started section for general usage information + we add a new section "Examples" (as it is done for example in the documentation of cvxpy [here](https://www.cvxpy.org/examples/index.html)) where we can list notebooks for all types of useful examples that comes to our mind?
But this is just a suggestion. If you have a strong different opinion, we can make it your way.

**Comment by jduerholt** [comment]
Would be fine for me, but note that what you see currently under getting started is a notebook ;)
