### ISSUE TITLE
Refactor SOBO

### ISSUE THREAD

**Issue by jduerholt** [experimental-design/bofire#35]
Refactor SOBO by using the get_acquisition_function method from botorch.

**Comment by jkleinekorte** [comment]
I prepared a first suggestion in this branch: https://github.com/experimental-design/bofire/tree/feature/refactor_SOBO

An open to do related to this issue: Shall we refactor qehvi and qnehvi similarly?

**Comment by bertiqwerty** [comment]
Closed with #36
