### ISSUE TITLE
Pydantic vs. Pyright

### ISSUE THREAD

**Issue by bertiqwerty** [experimental-design/bofire#41]
During working on #39 and #40 I noticed that Pydantic and Pyright do not seem to work well together. This is also indicated by all the `type: ignore` comments. Pydantic does a lot of magic in the background that is not accessible by type checkers. See also https://github.com/pydantic/pydantic/issues/3699.  Maybe we have to think about getting rid of one of the two. My current pro-and-con list looks as follows.

| pro pydantic | con pydantic (pro pyright/static type checking) |
|--------------|-------------------------|
|Pydantic actually does type checks during runtime.|Pyright gives you way faster feedback about problems with types that often indicate actual bugs namely during development in your IDE.|
|Pydantic has validators that can be used for simple transforms of the inputs, e.g., `List[InputFeature]->InputFeatures` https://github.com/experimental-design/bofire/blob/97411c7f902d0b1c46362dba9c2872e80caccc6a/bofire/domain/domain.py#L45-L54| Pydantic is not straight forward Python code and especially for not so experienced Python developers another hurdle to jump over before contributing to our library. This is in my opinion the strongest argument against Pydantic since we actually would welcome a adoption also by not so Python-experienced data scientists and researchers.|

Any thoughts anyone?

**Comment by evo-bschiller** [comment]
My initial thoughts:
pydantic and pyright solve very different problems.
Therefore, we should not discard one in order to use the other.

pydantic allows us to create model classes for holding data and verifying inputs during runtime, similar to dataclasses (but far more powerfull IMO).
pyright helps us to check / verify types at compile time.

If pyright does not play well with pydantic models, what about using mypy instead?
I read that it works well with pydantic (in contrast to pyright).
Would it be an option to try mypy instead or is its use required by some workflow?

**Comment by bertiqwerty** [comment]
I am skeptical that Mypy can, e.g., detect transformations that happen in validators as the one shown above. I will try this out.

**Comment by bertiqwerty** [comment]
Actually, I tried this already. But then inside the class it the type checker thinks it can be both things which is not always valid.

**Comment by bertiqwerty** [comment]
Ok. Since it seems that I am the only one who sees the additional entry barrier for new library contributors as significant drawback of Pydantic while understanding its technical benefits, this is my proposal for a compromise:
- We keep both, Pydantic and a static type checker (let's try keeping Pyright because we already are using it, but I am also open to using Mypy).
- We define the types of our core classes like `Domain`, `InputFeatures`, ... in a way that they describe the interface so that library users can use them as expected. For instance
  ```
  input_features: Union[InputFeatures, Sequence[InputFeature]] = Field(default_factory=lambda: InputFeatures())
  ```
- We put as little as possible convenience methods into our core classes. For example, we have a discussion about `add_feature` in #40. Usually, you know what kind of feature you are adding. So in this case, I even do not really see the additional convenience as benefit.
- For the inner workings of small (e.g., without `add_feature` and friends) core classes we tell the type checkers with `cast`s to not complain. 
- We avoid `# type: ignore` as much as possible.

If you agree, I could prepare a PR. @evo-bschiller, @jduerholt, @R-M-Lee

**Comment by jduerholt** [comment]
> * We define the types of our core classes like `Domain`, `InputFeatures`, ... in a way that they describe the interface so that library users can use them as expected. For instance
>   ```
>   input_features: Union[InputFeatures, Sequence[InputFeature]] = Field(default_factory=lambda: InputFeatures())
>   ```

One specific question to this: Why is this necessary, you can already use instantiate the input_features attribute from a list, this is handled by the validator for input features https://github.com/experimental-design/bofire/blob/97411c7f902d0b1c46362dba9c2872e80caccc6a/bofire/domain/domain.py#L47

So why is it needed to add also Sequence as input type?

**Comment by jduerholt** [comment]
> * We put as little as possible convenience methods into our core classes. For example, we have a discussion about `add_feature` in [Remove add features #40](https://github.com/experimental-design/bofire/pull/40). Usually, you know what kind of feature you are adding. So in this case, I even do not really see the additional convenience as benefit.

What is the reason of as little as possible convenience methods? Is it that they often cause troubles with pyright?

**Comment by bertiqwerty** [comment]
A compromise could be to have the types so that they describe the interface. That inside the class 

> > * We define the types of our core classes like `Domain`, `InputFeatures`, ... in a way that they describe the interface so that library users can use them as expected. For instance
> >   ```
> >   input_features: Union[InputFeatures, Sequence[InputFeature]] = Field(default_factory=lambda: InputFeatures())
> >   ```
> 
> One specific question to this: Why is this necessary, you can already use instantiate the input_features attribute from a list, this is handled by the validator for input features
> 
> https://github.com/experimental-design/bofire/blob/97411c7f902d0b1c46362dba9c2872e80caccc6a/bofire/domain/domain.py#L47
> 
> So why is it needed to add also Sequence as input type?

To make static type checkers work. This does not change the behavior at runtime.

**Comment by bertiqwerty** [comment]
> > * We put as little as possible convenience methods into our core classes. For example, we have a discussion about `add_feature` in [Remove add features #40](https://github.com/experimental-design/bofire/pull/40). Usually, you know what kind of feature you are adding. So in this case, I even do not really see the additional convenience as benefit.
> 
> What is the reason of as little as possible convenience methods? Is it that they often cause troubles with pyright?

Mainly, because smaller core classes have the advantage that we have to maintain less code. Further, static type checkers cannot be as helpful for maintenance of these Pydantic classes due to the validators that also transform input. We could think about putting convenience functions outside of Pydantic classes if they are really helpful.

**Comment by evo-bschiller** [comment]
I also am not a big fan of such convernience methods like
```
def add_to_list(self, x):
    self.my_list.append(x)
```
Of course, this has the benefit of being somehow prepared for doing some stuff LATER for every addition (e.g., certain checks, statistics, other cleanup).
But as long as this is not needed, it adds complexity and makes it seem like the method call is doing more than it actually is.

Therefore, i totally agree and vote for removing such helper functions.
I am also fine with all other proposed changes.

**Comment by jduerholt** [comment]
Ok, then let's remove the add features!

**Comment by DavidWalz** [comment]
Just want to add my support. I'm also for keeping the core interface as small as possible. Less methods is better for maintenance but also for users.

I really like that pydantic is part of the framework, because as soon as you build a FastAPI around it you need it anyways.
In Brain (bo/opti) we patched it around, but it would have been better to have made it part of opti.

**Comment by bertiqwerty** [comment]
I think we can close this.
