### ISSUE TITLE
How is it different from botorch?

### ISSUE THREAD

**Issue by pswpswpsw** [experimental-design/bofire#438]
Just curious? It looks like botorch can cover bofire?

**Comment by jduerholt** [comment]
Hi @pswpswpsw,

you are correct, BoFire's Bayesian optimization capabilities are based on BoTorch. Whereas BoTorch is a more low level highly modulay library for Bayesian optimization, BoFire is a more user friendly high-level library (comparabely to Meta's Ax) tailored towards chemical and engineering problems. It is easy to setup complex multiobjective optimization problems, using custom surrogates and use them for optimization over mixed domains including equality, inequality, NChooseK and other constraints. Furthermore, BoFire is based on pydantic and is fully serializeable and can be easily deployed behind a FastAPI. For more information, just have a look at our recent paper: https://arxiv.org/abs/2408.05040

In addition, we offer classical DoE approaches, like D-optimal designs.

Best,

Johannes
