### ISSUE TITLE
Scaled DoE test fails too often

### ISSUE THREAD

**Issue by dlinzner-bcs** [experimental-design/bofire#446]
This test in DoE fails too often https://github.com/experimental-design/bofire/blob/cffd409b6df5bb00396ec5b258ebb6f66cb7feca/tests/bofire/strategies/test_doe.py#L286

![image](https://github.com/user-attachments/assets/40ac76cd-02ea-4b38-913d-8f2569b28cfb)

**Comment by dlinzner-bcs** [comment]
@bertiqwerty

**Comment by jduerholt** [comment]
@Osburg: any ideas what is the problem?

**Comment by Osburg** [comment]
Hey @jduerholt @dlinzner-bcs,

This is probably not a satisfying answer, but in the setting of a linear model, a low dimensional space domain and a small number of candidates there seem to be local minima ipopt ends up in. Ipopt typically exits with a convergence to acceptable tolerance in cases where the test fails. I assume the reason might be that using only 4 candidates leads with relatively high probability to the situation that all experiments are concentrated in the same region of the design space and ipopt won't find the optimal solutions with one candidate in each corners, but instead it approaches a local minimum which typically looks like this
```
[[-0.     1.   ]
 [-0.    -0.   ]
 [-0.    -0.   ]
 [ 1.     0.287]]
``` 
I tried to increase the number of candidates, with 6 candidates the test ran successfully for 100 times in a row. So I'd suggest to slightly increase the number of candidates. Alternatively, one could lower the (acceptable) tolerance for convergence, but this would require to give access to the `ipopt_options` of `find_local_max_ipopt()` in the `DoEStrategy` i guess... 

Also sry for general inactivity recently, I have a submission deadline in 2 weeks :/

Cheers
Aaron :)
