### ISSUE TITLE
Change categorical seperator

### ISSUE THREAD

**Issue by jduerholt** [experimental-design/bofire#66]
Currently, a underscore `_` is used as categorical seperator https://github.com/experimental-design/bofire/blob/629c48aab38d4172cc2da0d5b4b5b7b432b66a92/bofire/domain/features.py#L27

This creates problems in the inverse_transform if an underscore is also present in the feature name of the categorical feature. At least in `from_one_hot_encoding`. Either we switch to a more rare seperator or we implement the from methods in a way that they are not failing when the column seperator is also used as a normal letter in the feature name. This would be the preferred solution.

**Comment by evo-nlueck** [comment]
Maybe the pandas functions `pd.get_dummies` and `pd.from_dummies` can be useful. They also use a separator (default value "_"), though. If the separator should be changed to "a more rare separator", it could also be a multi-character string to make collisions with feature names even less likely.

**Comment by jduerholt** [comment]
Solved with this PR: https://github.com/experimental-design/bofire/pull/200
