### ISSUE TITLE
Port DoE from basf/mbo

### ISSUE THREAD

**Issue by bertiqwerty** [experimental-design/bofire#68]
Details:
- Move DoE into BoFire repo.
- Replace opti.Problem by bofire.domain.Domain.
- Wrap it into a strategy.

**Comment by jduerholt** [comment]
- Dependencies for DoE should be optional
- fixed experiments should be read from domain.candidates

**Comment by dlinzner-bcs** [comment]
I would be interested in tacking this tomorrow :)

**Comment by WaStCo** [comment]
Hi @dlinzner-bcs , did you have the chance to look into it? Looking specifically to the function to generate the number of experiments (as requested by a collaboration project). Thanks!
