### ISSUE TITLE
Finalize the opti/bofire mappers

### ISSUE THREAD

**Issue by jduerholt** [experimental-design/bofire#77]
We want to finalize the PR on the opti/bofire mapper: https://github.com/experimental-design/bofire/pull/6

**Comment by rosonaeldred** [comment]
We discussed this this week. Emphasis given on mapping between the serialized jsons. 

I have a question: are domain.outputs automatically objectives? That's what it looks like, and that it defaults to maximize. 
If someone has a minute and can help me figure out:  (@jduerholt ? @dlinzner-bcs ? @jkleinekorte ?)
1. can you have outputs which are not objectives and
2. how to set to not just maximize (e.g. minimize, close to target)
https://github.com/experimental-design/bofire/blob/d0f4d76dd08dab256ffa9fe47dbf1e0623c17c66/bofire/data_models/domain/features.py#L489

i'd appreciate it, given i'm using domain this week to use the doe ported-to-bofire.


`domain.output_features = [ContinuousOutput(key=f"y{i}") for i in range(1, n_y+1)] `

Gives me 

`output_features=Outputs(type='Outputs', features=[ContinuousOutput(type='ContinuousOutput', key='y1', objective=MaximizeObjective(type='MaximizeObjective', w=1.0, lower_bound=0, upper_bound=1), unit=None)]),`
[etc]

**Comment by jduerholt** [comment]
Hi Rosona, 

objects in domain.outputs are not automatically objectives. They are `OutputFeature`s. And an OutputFeature has an attribute `objective` to which an objective objective can be assigned, but you can also assign `None`, than you have an output feature which should be not influence the optimization process.

To set output features with another object you just do the following:

```
from bofire.data_models.objectives.api import MinimizeObjective, CloseToTargetObjective
from bofire.data_models.features.api import ContinuousOutput

a = ContinuousOutput(key="a", objective = MinimizeObjective(w=1))
b = ContinuousOutput(key="b", objective = CloseToTargetObjective(w=1, target_value=2, exponent=2))
```

I hope this helps ;)

Best,

Johannes

**Comment by rosonaeldred** [comment]
Question for @jduerholt  @DavidWalz  and @R-M-Lee fyi: 

Looking at the outputs and objectives conversion from opti to domain, I have some questions, which boil down to mismatched signatures of various methods.  

**CloseToTargetObjective :** 

bofire domain context question: how/where is weight used? 
https://github.com/experimental-design/bofire/blob/main/bofire/data_models/objectives/target.py#L26
Example above: CloseToTargetObjective(w=1, target_value=2, exponent=2)  


In opti, we have a 'tolerance' for CloseToTarget. I don't think that's the weight w in domain. 
Follow-up question then:  how is 'tolerance' handled?
Does it somehow need to move to the constraints portion of the object? 
'tolerance: only when used as output constraint. distance to target below which no further improvement is required' 
@DavidWalz 
https://github.com/basf/mopti/blob/c66a1b4e8be54856ae33b20962826a6fa3cc3d37/opti/objective.py#L99


[The core point is: do I ignore/drop some information or does it get converted to other information]

**Comment by jduerholt** [comment]
Hi Rosona,

The weight is something different, it is used for example in AdditiveSobo/multiplicative to add up the objective, in the other strategies it is ignored. In the conversion, I would always set it to 1. 

Close to target has no `tolerance` anymore as it was used in opti just in output constraints, if you want to have an output constraint which constraints one output to a target (range), then you should use the `TargetObjective` instead.

**Comment by rosonaeldred** [comment]
Hey @jduerholt , is this how to handle non-continuous non-objective Outputs? 
https://github.com/experimental-design/bofire-converters/blob/main/opti_to_domain.py#L99

Opti info might look like: 
    outputs = Parameters(
        [
            Discrete("meetings", domain=[0.0, 1.0, 2.0, 3.0]),
            Continuous("coffee", domain=[0, 20.0]),
            Continuous("seriousness", domain=[0, 10.0]),
            Categorical("animal", domain=["cat", "dog", "monkey"])
        ]
    )
    
    objectives = Objectives(
        [
            Minimize("meetings", target=2),
            Maximize("coffee", target=4),
            CloseToTarget("seriousness", target=5, exponent=2, tolerance=1.1),
        ]
    )
    
    then the output looks like 
    
    [MinimizeObjective(type='MinimizeObjective', w=1, lower_bound=0, upper_bound=1),
 MaximizeObjective(type='MaximizeObjective', w=1, lower_bound=0, upper_bound=1),
 CloseToTargetObjective(type='CloseToTargetObjective', w=1, target_value=5.0, exponent=2.0),
 Output(type='categorical', key='animal', objective=None)]

**Comment by DavidWalz** [comment]
> 'tolerance: only when used as output constraint. distance to target below which no further improvement is required'

@rosonaeldred we also used objectives as output constraints (black box constraints) because the functionality is largely identical. As the docstring state the tolerance part was only considered in that case. As we hardly used this I recommend ignoring that part in the conversion.

**Comment by rosonaeldred** [comment]
@DavidWalz  thanks for weighing in, I will do it that way then.  I assume target is the same, then? 

> Also, a related question on how to handle 'target' for Minimize/Maximize objectives in opti but now in bofire
> 'target: only when used as output constraint. value above which no further improvement is required"
> https://github.com/basf/mopti/blob/c66a1b4e8be54856ae33b20962826a6fa3cc3d37/opti/objective.py#L61

**Comment by bertiqwerty** [comment]
Yes. We have this now in a separate repo.
https://github.com/experimental-design/bofire-converters
