### ISSUE TITLE
Add tests for fenced code in documentation

### ISSUE THREAD

**Issue by WaStCo** [experimental-design/bofire#97]
We looked at three methodologies to add tests covering fenced code in the documentation:

1. DocTest
  - Requires `>>>` prior to code, degrades readability 
2. phmdoctest 
  - Adds dependency to additional small package
3. Manual parsing of code blocks
  - Prone for edge cases

Due to these, we decided to parse the code blocks and go with option 3.

**Comment by jkleinekorte** [comment]
will be added with PR #105
